// Generated by gencpp from file ros_tut/servo.msg
// DO NOT EDIT!


#ifndef ROS_TUT_MESSAGE_SERVO_H
#define ROS_TUT_MESSAGE_SERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tut
{
template <class ContainerAllocator>
struct servo_
{
  typedef servo_<ContainerAllocator> Type;

  servo_()
    : first(0)
    , second(0)
    , third(0)  {
    }
  servo_(const ContainerAllocator& _alloc)
    : first(0)
    , second(0)
    , third(0)  {
    }



   typedef int16_t _first_type;
  _first_type first;

   typedef int16_t _second_type;
  _second_type second;

   typedef int16_t _third_type;
  _third_type third;




  typedef boost::shared_ptr< ::ros_tut::servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tut::servo_<ContainerAllocator> const> ConstPtr;

}; // struct servo_

typedef ::ros_tut::servo_<std::allocator<void> > servo;

typedef boost::shared_ptr< ::ros_tut::servo > servoPtr;
typedef boost::shared_ptr< ::ros_tut::servo const> servoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tut::servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tut::servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_tut

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_tut': ['/home/eeit/roboarm/catkin_ws/src/ros_tut/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_tut::servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tut::servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tut::servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tut::servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tut::servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tut::servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tut::servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a857454193b3801feabc5fd6d0dba368";
  }

  static const char* value(const ::ros_tut::servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa857454193b3801fULL;
  static const uint64_t static_value2 = 0xeabc5fd6d0dba368ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tut::servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tut/servo";
  }

  static const char* value(const ::ros_tut::servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tut::servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 first\n\
int16 second\n\
int16 third\n\
";
  }

  static const char* value(const ::ros_tut::servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tut::servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
      stream.next(m.third);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tut::servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tut::servo_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<int16_t>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<int16_t>::stream(s, indent + "  ", v.second);
    s << indent << "third: ";
    Printer<int16_t>::stream(s, indent + "  ", v.third);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUT_MESSAGE_SERVO_H
