"""autogenerated by genpy from brazo_fer/ReadServos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import brazo_fer.msg

class ReadServos(genpy.Message):
  _md5sum = "eb601df5ba86278a5ceaf5eea9e7da64"
  _type = "brazo_fer/ReadServos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Servos posicion
Servos estado
Servos corriente

================================================================================
MSG: brazo_fer/Servos
int16 base
int16 arti1
int16 arti2
int16 arti3
int16 pinza

"""
  __slots__ = ['posicion','estado','corriente']
  _slot_types = ['brazo_fer/Servos','brazo_fer/Servos','brazo_fer/Servos']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       posicion,estado,corriente

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReadServos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.posicion is None:
        self.posicion = brazo_fer.msg.Servos()
      if self.estado is None:
        self.estado = brazo_fer.msg.Servos()
      if self.corriente is None:
        self.corriente = brazo_fer.msg.Servos()
    else:
      self.posicion = brazo_fer.msg.Servos()
      self.estado = brazo_fer.msg.Servos()
      self.corriente = brazo_fer.msg.Servos()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_15h.pack(_x.posicion.base, _x.posicion.arti1, _x.posicion.arti2, _x.posicion.arti3, _x.posicion.pinza, _x.estado.base, _x.estado.arti1, _x.estado.arti2, _x.estado.arti3, _x.estado.pinza, _x.corriente.base, _x.corriente.arti1, _x.corriente.arti2, _x.corriente.arti3, _x.corriente.pinza))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.posicion is None:
        self.posicion = brazo_fer.msg.Servos()
      if self.estado is None:
        self.estado = brazo_fer.msg.Servos()
      if self.corriente is None:
        self.corriente = brazo_fer.msg.Servos()
      end = 0
      _x = self
      start = end
      end += 30
      (_x.posicion.base, _x.posicion.arti1, _x.posicion.arti2, _x.posicion.arti3, _x.posicion.pinza, _x.estado.base, _x.estado.arti1, _x.estado.arti2, _x.estado.arti3, _x.estado.pinza, _x.corriente.base, _x.corriente.arti1, _x.corriente.arti2, _x.corriente.arti3, _x.corriente.pinza,) = _struct_15h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_15h.pack(_x.posicion.base, _x.posicion.arti1, _x.posicion.arti2, _x.posicion.arti3, _x.posicion.pinza, _x.estado.base, _x.estado.arti1, _x.estado.arti2, _x.estado.arti3, _x.estado.pinza, _x.corriente.base, _x.corriente.arti1, _x.corriente.arti2, _x.corriente.arti3, _x.corriente.pinza))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.posicion is None:
        self.posicion = brazo_fer.msg.Servos()
      if self.estado is None:
        self.estado = brazo_fer.msg.Servos()
      if self.corriente is None:
        self.corriente = brazo_fer.msg.Servos()
      end = 0
      _x = self
      start = end
      end += 30
      (_x.posicion.base, _x.posicion.arti1, _x.posicion.arti2, _x.posicion.arti3, _x.posicion.pinza, _x.estado.base, _x.estado.arti1, _x.estado.arti2, _x.estado.arti3, _x.estado.pinza, _x.corriente.base, _x.corriente.arti1, _x.corriente.arti2, _x.corriente.arti3, _x.corriente.pinza,) = _struct_15h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_15h = struct.Struct("<15h")
