"""autogenerated by genpy from brazo_fer/Servos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Servos(genpy.Message):
  _md5sum = "6be90daad19b44888c6ef8582506a939"
  _type = "brazo_fer/Servos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 base
int16 arti1
int16 arti2
int16 arti3
int16 pinza

"""
  __slots__ = ['base','arti1','arti2','arti3','pinza']
  _slot_types = ['int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base,arti1,arti2,arti3,pinza

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Servos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.base is None:
        self.base = 0
      if self.arti1 is None:
        self.arti1 = 0
      if self.arti2 is None:
        self.arti2 = 0
      if self.arti3 is None:
        self.arti3 = 0
      if self.pinza is None:
        self.pinza = 0
    else:
      self.base = 0
      self.arti1 = 0
      self.arti2 = 0
      self.arti3 = 0
      self.pinza = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5h.pack(_x.base, _x.arti1, _x.arti2, _x.arti3, _x.pinza))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.base, _x.arti1, _x.arti2, _x.arti3, _x.pinza,) = _struct_5h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5h.pack(_x.base, _x.arti1, _x.arti2, _x.arti3, _x.pinza))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.base, _x.arti1, _x.arti2, _x.arti3, _x.pinza,) = _struct_5h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5h = struct.Struct("<5h")
