// Generated by gencpp from file brazo_fer/WriteServos.msg
// DO NOT EDIT!


#ifndef BRAZO_FER_MESSAGE_WRITESERVOS_H
#define BRAZO_FER_MESSAGE_WRITESERVOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <brazo_fer/Servos.h>
#include <brazo_fer/Servos.h>
#include <brazo_fer/Servos.h>

namespace brazo_fer
{
template <class ContainerAllocator>
struct WriteServos_
{
  typedef WriteServos_<ContainerAllocator> Type;

  WriteServos_()
    : posicion()
    , velocidad()
    , par()  {
    }
  WriteServos_(const ContainerAllocator& _alloc)
    : posicion(_alloc)
    , velocidad(_alloc)
    , par(_alloc)  {
    }



   typedef  ::brazo_fer::Servos_<ContainerAllocator>  _posicion_type;
  _posicion_type posicion;

   typedef  ::brazo_fer::Servos_<ContainerAllocator>  _velocidad_type;
  _velocidad_type velocidad;

   typedef  ::brazo_fer::Servos_<ContainerAllocator>  _par_type;
  _par_type par;




  typedef boost::shared_ptr< ::brazo_fer::WriteServos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brazo_fer::WriteServos_<ContainerAllocator> const> ConstPtr;

}; // struct WriteServos_

typedef ::brazo_fer::WriteServos_<std::allocator<void> > WriteServos;

typedef boost::shared_ptr< ::brazo_fer::WriteServos > WriteServosPtr;
typedef boost::shared_ptr< ::brazo_fer::WriteServos const> WriteServosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brazo_fer::WriteServos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brazo_fer::WriteServos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace brazo_fer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'brazo_fer': ['/home/eeit/roboarm/catkin_ws/src/brazo_fer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::brazo_fer::WriteServos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brazo_fer::WriteServos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brazo_fer::WriteServos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brazo_fer::WriteServos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brazo_fer::WriteServos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brazo_fer::WriteServos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brazo_fer::WriteServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9551946156ffa6c4d13c8c60abd574c1";
  }

  static const char* value(const ::brazo_fer::WriteServos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9551946156ffa6c4ULL;
  static const uint64_t static_value2 = 0xd13c8c60abd574c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::brazo_fer::WriteServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brazo_fer/WriteServos";
  }

  static const char* value(const ::brazo_fer::WriteServos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brazo_fer::WriteServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Servos posicion\n\
Servos velocidad\n\
Servos par\n\
\n\
================================================================================\n\
MSG: brazo_fer/Servos\n\
int16 base\n\
int16 arti1\n\
int16 arti2\n\
int16 arti3\n\
int16 pinza\n\
";
  }

  static const char* value(const ::brazo_fer::WriteServos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brazo_fer::WriteServos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posicion);
      stream.next(m.velocidad);
      stream.next(m.par);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WriteServos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brazo_fer::WriteServos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brazo_fer::WriteServos_<ContainerAllocator>& v)
  {
    s << indent << "posicion: ";
    s << std::endl;
    Printer< ::brazo_fer::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.posicion);
    s << indent << "velocidad: ";
    s << std::endl;
    Printer< ::brazo_fer::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.velocidad);
    s << indent << "par: ";
    s << std::endl;
    Printer< ::brazo_fer::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.par);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAZO_FER_MESSAGE_WRITESERVOS_H
