set(_CATKIN_CURRENT_PACKAGE "arm_control")
set(arm_control_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(arm_control_DEPRECATED "")
set(arm_control_VERSION "0.0.0")
set(arm_control_BUILD_DEPENDS "message_generation")
set(arm_control_RUN_DEPENDS "message_runtime" "controller_manager")
set(arm_control_BUILDTOOL_DEPENDS "catkin")